'use strict';
const test = require('node:test');
const assert = require('node:assert');
const { isSignal, normalizeKey, mineSignals } = require('../learn-mine');

// 应保留：泛化的长期偏好（祈使、可独立成规则）
const KEEP = [
  '不要折行',
  '不要每次都打包，直接在开发版本查看即可',
  '不要在终端打开目录，而是打开对应的应用',
  '不要创建新仓库',
  '必须点创建key才能添加，回车不要触发',
];

// 应过滤：一次性 / 不具泛化性 / 噪声
const DROP = [
  'Caveat: The messages below were generated by the user',          // harness 前言
  'Warning: Encountered two children with the same key',            // 粘贴日志
  '路径错误 应该是/Users/ully/githubprojects/podcast',                // 绝对路径
  '地址显示不正确，应该是tokenbank的服务器地址',                       // bug 症状
  '修改这里，不要改设备展示',                                          // 指代当前会话
  '改成600',                                                          // 纯数值
  'AI是领域，不是关键词',                                             // 澄清式更正（无祈使）
  '不是代码，应该是3段prompt',                                        // 澄清式更正
  'apkey未命名 sk-local-9eb 应该是 test123',                          // 凭证片段
];

test('isSignal keeps generalizable durable preferences', () => {
  for (const t of KEEP) assert.equal(isSignal(t), true, `should keep: ${t}`);
});

test('isSignal drops one-off / non-generalizable / noise', () => {
  for (const t of DROP) assert.equal(isSignal(t), false, `should drop: ${t}`);
});

test('imperative survives even with a clarification clause', () => {
  // 含"不要…"祈使 → 即便有"不是…"澄清也保留
  assert.equal(isSignal('不是cursor问题，不要简单只看某个，要保证泛化性'), true);
});

test('mineSignals aggregates across sessions, counts once per session, sorts by count', () => {
  const traces = [
    { agent_id: 'claude-code', project: 'p1', steps: [
      { kind: 'user', text: '不要折行' }, { kind: 'user', text: '不要折行' }, // 同会话重复只计一次
      { kind: 'assistant', text: 'ok' },
    ] },
    { agent_id: 'codex', project: 'p2', steps: [
      { kind: 'user', text: '不要折行' },
      { kind: 'user', text: '不要创建新仓库' },
    ] },
  ];
  const out = mineSignals(traces);
  const fold = out.find(c => c.key === normalizeKey('不要折行'));
  assert.equal(fold.count, 2, 'two sessions, not three (intra-session dedup)');
  assert.deepEqual(fold.agents.sort(), ['claude-code', 'codex']);
  assert.equal(out[0].count >= out[out.length - 1].count, true, 'sorted desc by count');
});
